apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: app-ingress
spec:
  rules:
  - host: www.arun.com
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80
        path: /app1
      - backend:
          serviceName: backend
          servicePort: 80
        path: /app2
