apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend
  labels:
    app: mongodb
    tier: backend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: mongo
        image: mongo:3.4
        ports:
          - containerPort: 7501
