apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 7474
    protocol: TCP
    targetPort: 8088
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - port: 7501
    protocol: TCP
    targetPort: 8089
  selector:
    app: backend
